version: "3.8"

services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - finance-network

  test_db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    networks:
      - finance-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-stage # Specify the target stage for development
    restart: on-failure
    volumes:
      - .:/app
      - /app/tmp # Necessary to ensure live-reload tools like air work correctly
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Add environment variables for test database if needed
    depends_on:
      db:
        condition: service_healthy
      test_db:
        condition: service_healthy
    networks:
      - finance-network

networks:
  finance-network:

volumes:
  db_data:
  test_db_data:
